const fakeResults = [
  {
    flightNumber: "TK123",
    departure: "IST",
    arrival: "JFK",
    departureTime: "08:00",
    arrivalTime: "14:00",
    duration: "6h",
    price: "$500",
  },
  {
    flightNumber: "TK456",
    departure: "JFK",
    arrival: "IST",
    departureTime: "15:00",
    arrivalTime: "21:00",
    duration: "6h",
    price: "$550",
  },
  {
    flightNumber: "TK789",
    departure: "IST",
    arrival: "LHR",
    departureTime: "10:00",
    arrivalTime: "12:00",
    duration: "2h",
    price: "$400",
  },
  {
    flightNumber: "TK111",
    departure: "LHR",
    arrival: "IST",
    departureTime: "14:00",
    arrivalTime: "18:00",
    duration: "4h",
    price: "$450",
  },
  // Sıralamayı test etmek için aynı kalkış ve varış noktasına sahip uçuşlar
  {
    flightNumber: "TK222",
    departure: "JFK",
    arrival: "LHR",
    departureTime: "09:30",
    arrivalTime: "15:30",
    duration: "6h",
    price: "$600",
  },
  {
    flightNumber: "TK888",
    departure: "JFK",
    arrival: "LHR",
    departureTime: "18:30",
    arrivalTime: "00:30",
    duration: "6h",
    price: "$720",
  },
  {
    flightNumber: "TK333",
    departure: "JFK",
    arrival: "LHR",
    departureTime: "11:00",
    arrivalTime: "18:00",
    duration: "7h",
    price: "$620",
  },
  {
    flightNumber: "TK444",
    departure: "JFK",
    arrival: "LHR",
    departureTime: "12:30",
    arrivalTime: "14:30",
    duration: "2h",
    price: "$640",
  },

  {
    flightNumber: "TK999",
    departure: "JFK",
    arrival: "LHR",
    departureTime: "20:00",
    arrivalTime: "02:00",
    duration: "6h",
    price: "$740",
  },
  {
    flightNumber: "TK555",
    departure: "JFK",
    arrival: "LHR",
    departureTime: "14:00",
    arrivalTime: "18:00",
    duration: "4h",
    price: "$660",
  },
  {
    flightNumber: "TK777",
    departure: "JFK",
    arrival: "LHR",
    departureTime: "17:00",
    arrivalTime: "20:00",
    duration: "3h",
    price: "$700",
  },

  {
    flightNumber: "TK666",
    departure: "JFK",
    arrival: "LHR",
    departureTime: "15:30",
    arrivalTime: "21:30",
    duration: "6h",
    price: "$680",
  },
];

module.exports = fakeResults;
